### ISSUE TITLE
the future of importly — fallbacks, local dependencies, pika

### ISSUE THREAD

**Issue by chase-moskal** [chase-moskal/importly#15]
so, i misunderstood the import maps spec, and thought that fallbacks was to set alternative sources, so that if say, unpkg isn't loading, then it will kick in and fetch from jsdelivr instead

this is *not* how import maps work, apparently this only works for replacing builtin modules

so i thought i added a cool new feature to importly, but i actually broke it. it's fixed now, and i've added a testing page to cover it

this is upsetting to me, because i don't want to have to rely on the availability of one CDN URL

i suppose the correct answer for this, is local hosting?

now, local hosting is something that `@pika/web` seems to do well..

now i'm wondering if importly should integrate with pika's configuration, actually becoming an import map generator for pika

i like the idea -- this could mean abandoning importly's custom syntax, reading pika's package json field instead, and then being capable to produce an import map that either points to `web_modules`, or to `unpkg`, or to `jsdelivr`

i like this

i think this might even still allow importly to operate in-browser, literally reading the package.json or having it embedded

**Comment by chase-moskal** [comment]
okay i've done some playing around, here's my thoughts

- [x] abandon `importly.config` — it was fun
- [x] use `package.json` dependencies — this doesn't actually necessitate npm usage :dark_sunglasses: 
- [x] importly host option can be `node_modules`, ~~`web_modules`,~~ `unpkg`, or `jsdelivr`
  - **web_modules not supported**
- [x] seamless interoperation between four possible sources to load modules
  - **users can swap out which 'generator' is being used via 'host' cli option**
- [x] ~~pika's web_modules will be the most optimal~~
- [x] npm's node_modules will be the best for debugging and local development
- [x] cdn's like unpkg and jsdelivr are cool alternatives to avoid installing anything locally
- [x] in ALL SCENARIOS, bare specifier imports are being resolved via import maps
- [x] if you want to avoid import maps, you stop using importly and start using a bundler ~~or pika web_modules directly~~
- [x] ~~importly should be able to operate in-browser without any build step, or as a command-line tool~~

**Comment by chase-moskal** [comment]
huge refactor done in `importly@0.1.0-dev.0`

**Comment by Nashorn** [comment]
...Does this mean importmap paths will point to node_modules instead of cdn/jsdelivr?

**Comment by chase-moskal** [comment]
@Nashorn 

the current version of importly supports node_modules or the jsdelivr or unpkg cdn's:

```sh
# import map paths will point to node_modules
importly --host node_modules < package.json > dist/importmap.json

# import map paths will point to the unpkg cdn
importly --host unpkg< package.json > dist/importmap.json

# import map paths will point to the jsdelivr cdn
importly --host jsdelivr < package.json > dist/importmap.json
```
