### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by mikestaub** [chase-moskal/importly#33]
When using react-router-dom it is mapping to the esm code in node_modules.

Is there a way to use commonjs only? ( prefer main to module in package.json )

**Comment by chase-moskal** [comment]
@mikestaub hello, this is an interesting issue.

can you help me understand this case, where you're using importmaps in conjunction with commonjs?

off the top of my head, i might assume import maps is an exclusively esm-oriented feature?

**Comment by mikestaub** [comment]
For example, if I want to use react-router in my import-map, the exported module is in commonjs format: https://ga.jspm.io/npm:react-router@6.2.1/main.js

**Comment by chase-moskal** [comment]
@mikestaub i'm confused, because that particular `main.js` appears to be an esm file, not commonjs (i see import/export statements, not require statements)

i'm personally only familiar using import maps in esm-only projects.

**Comment by mikestaub** [comment]
It must have been my transpiled code then that was throwing that error.
